version: '3.8'
services:
  ui:
    image: rpitv/glimpse-ui
    ports:
      - "3000:3000"
      - "5862:5862"
    restart: unless-stopped
    env_file:
      - .env
    command: npm run dev
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - glimpse_network
networks:
  glimpse_network:
    external: true
    name: glimpse_network
