version: '3.9'
services:
  db:
    image: postgres:14
    restart: unless-stopped
    ports:
      - "5432:5432"
    volumes:
      - .db-data:/var/lib/postgresql/data
    env_file:
      - .env
    networks:
      - glimpse_network

  redis:
    image: redis:7
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - .redis-data:/data
    networks:
      - glimpse_network

  rabbitmq:
    image: rabbitmq:3.10-management
    restart: unless-stopped
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - glimpse_network

networks:
  glimpse_network:
    name: glimpse_network
