version: '3.8'
services:
  api:
    depends_on:
      - db
    build:
      context: ..
      dockerfile: ./docker/api/Dockerfile
    ports:
      - "4000:80"
    restart: unless-stopped
    env_file:
      - ../.env
  db:
    image: postgres:12.3-alpine
    restart: unless-stopped
    env_file:
      - db/.env
