version: '3.8'
services:
  api:
    depends_on:
      - db
    image: rpitv/glimpse-api
    ports:
      - "4000:4000"
    restart: unless-stopped
    env_file:
      - ../.env
  db:
    image: postgres:12.3-alpine
    restart: unless-stopped
    volumes:
      - ./db/postgres-data:/var/lib/postgresql/data
    env_file:
      - db/.env
