language: node_js
node_js:
  - 12
before_install:
  - printf "@fortawesome:registry=https://npm.fontawesome.com/\n//npm.fontawesome.com/:_authToken=\${NPM_TOKEN}" > .npmrc
install:
  - npm i
  - npm i -g codecov
  - npm i -g wait-on
script:
  - npm run lint
  - npm run test
  - codecov
  - npm run build
  - npm start & wait-on http://localhost:3000
  - cypress run --record --key ${CYPRESS_TOKEN}
