language: node_js
node_js:
  - 12
before_install:
  - printf "@fortawesome:registry=https://npm.fontawesome.com/\n//npm.fontawesome.com/:_authToken=\${NPM_TOKEN}" > .npmrc
install:
  - npm i -g codecov
script:
  - npm run test
  - npm run build
  - codecov
